// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice The official SP1 Verifier Interface standard (sp1-contracts)
interface ISP1Verifier {
    function verifyProof(
        bytes32 programVKey,
        bytes calldata publicValues,
        bytes calldata proofBytes
    ) external view;
}

/// @title PiNS Layer-2 Anchor
/// @notice Secures the PIVX Name Service sparse merkle tree state using SP1 ZK-SNARKs
contract PiNSAnchor {
    // --- ROLES & STATE PACKING ---
    // Slot 0 (20 bytes)
    address public owner;
    
    // Slot 1 (20 bytes + 4 bytes = 24 bytes) - Storage Packed!
    address public sequencer; // The specific wallet authorized to submit batches
    uint32 public currentBlockHeight; // Layer-2 current block height

    // Slot 2 (20 bytes)
    address public sp1Verifier;

    // Slot 3 (32 bytes)
    bytes32 public programVkey;

    // Slot 4 (32 bytes)
    bytes32 public currentRoot;

    // Slot 5
    /// @notice Maps a historically valid Merkle Root directly to the PIVX Block Height it represents
    mapping(bytes32 => uint32) public rootHistory;

    // --- MODERN STANDARD: CUSTOM ERRORS ---
    error Unauthorized();
    error NotSequencer();
    error InvalidOldRoot(bytes32 expected, bytes32 provided);
    error InvalidBlockHeight(uint32 current, uint32 provided);
    error InvalidAddress();
    error InvalidVKey();
    error InvalidRoot();
    error InvalidPublicValues();

    // --- EVENTS ---
    event RootUpdated(bytes32 indexed oldRoot, bytes32 indexed newRoot, uint32 endBlockHeight);
    event ProgramUpgraded(bytes32 indexed oldVkey, bytes32 indexed newVkey);
    event SequencerUpdated(address indexed oldSequencer, address indexed newSequencer);
    event VerifierUpdated(address indexed oldVerifier, address indexed newVerifier);
    event OwnershipTransferred(address indexed oldOwner, address indexed newOwner);

    // --- MODIFIERS ---
    modifier onlyOwner() {
        if (msg.sender != owner) revert Unauthorized();
        _;
    }

    modifier onlySequencer() {
        // Owner serves as a fallback sequencer just in case
        if (msg.sender != sequencer && msg.sender != owner) revert NotSequencer();
        _;
    }

    constructor(
        address _sp1Verifier,
        bytes32 _programVkey,
        bytes32 _genesisRoot,
        uint32 _genesisBlockHeight
    ) {
        if (_sp1Verifier == address(0)) revert InvalidAddress();
        if (_programVkey == bytes32(0)) revert InvalidVKey();
        if (_genesisRoot == bytes32(0)) revert InvalidRoot();

        owner = msg.sender;
        sequencer = msg.sender;
        sp1Verifier = _sp1Verifier;
        programVkey = _programVkey;

        currentRoot = _genesisRoot;
        currentBlockHeight = _genesisBlockHeight;

        rootHistory[_genesisRoot] = _genesisBlockHeight;

        emit OwnershipTransferred(address(0), msg.sender);
        emit SequencerUpdated(address(0), msg.sender);
        emit RootUpdated(bytes32(0), _genesisRoot, _genesisBlockHeight);
    }

    /// @notice Submits a new batch of PiNS transactions from the Sequencer
    /// @param proofBytes The proof generated by SP1 host prover
    /// @param publicValues The ABI encoded public values (oldRoot, newRoot, endBlockHeight)
    function commitBatch(bytes calldata proofBytes, bytes calldata publicValues) external onlySequencer {
        // Strict payload validation (3 * 32 bytes = 96 bytes expected)
        if (publicValues.length != 96) revert InvalidPublicValues();

        // 1. Decode the public values exactly as your Rust Host script encoded them
        (bytes32 oldRoot, bytes32 newRoot, uint32 endBlockHeight) = abi.decode(
            publicValues,
            (bytes32, bytes32, uint32)
        );

        if (newRoot == bytes32(0)) revert InvalidRoot();

        // 2. Enforce absolute chronological progression using Gas-Efficient Custom Errors
        if (oldRoot != currentRoot) revert InvalidOldRoot(currentRoot, oldRoot);
        if (endBlockHeight <= currentBlockHeight) revert InvalidBlockHeight(currentBlockHeight, endBlockHeight);

        // 3. Cryptographically verify the Zero-Knowledge Proof via SP1 Verifier Gateway
        ISP1Verifier(sp1Verifier).verifyProof(programVkey, publicValues, proofBytes);

        // 4. Update the official state
        currentRoot = newRoot;
        currentBlockHeight = endBlockHeight;

        // 5. Save the root mapped to its PIVX block height
        rootHistory[newRoot] = endBlockHeight;

        emit RootUpdated(oldRoot, newRoot, endBlockHeight);
    }

    /// @notice Allows an API user to check if a specific root is valid and what block it belongs to
    /// @return The PIVX block height at which this root was confirmed, or 0 if it is invalid/forged.
    function verifyRootValidity(bytes32 _root) external view returns (uint32) {
        return rootHistory[_root];
    }

    // ==========================================
    // ADMIN UPGRADEABILITY & MANAGEMENT FUNCTIONS
    // ==========================================

    /// @notice Allows the owner to upgrade the Rust program verification key
    function upgradeProgram(bytes32 _newProgramVkey) external onlyOwner {
        if (_newProgramVkey == bytes32(0)) revert InvalidVKey();
        bytes32 oldVkey = programVkey;
        programVkey = _newProgramVkey;
        emit ProgramUpgraded(oldVkey, _newProgramVkey);
    }

    /// @notice Changes the wallet authorized to submit ZK proofs
    function updateSequencer(address _newSequencer) external onlyOwner {
        if (_newSequencer == address(0)) revert InvalidAddress();
        address oldSequencer = sequencer;
        sequencer = _newSequencer;
        emit SequencerUpdated(oldSequencer, _newSequencer);
    }

    /// @notice Updates the SP1 Gateway Address if Succinct Network pushes an official contract upgrade
    function updateVerifier(address _newVerifier) external onlyOwner {
        if (_newVerifier == address(0)) revert InvalidAddress();
        address oldVerifier = sp1Verifier;
        sp1Verifier = _newVerifier;
        emit VerifierUpdated(oldVerifier, _newVerifier);
    }

    /// @notice Transfers contract ownership to a new address
    function transferOwnership(address _newOwner) external onlyOwner {
        if (_newOwner == address(0)) revert InvalidAddress();
        address oldOwner = owner;
        owner = _newOwner;
        emit OwnershipTransferred(oldOwner, _newOwner);
    }
}